### ISSUE TITLE
Add on-off support to zones.

### ISSUE THREAD

**Issue by Swamp-Ig** [Swamp-Ig/izone_custom_component#2]
Details to come...

**Comment by Swamp-Ig** [comment]
Hmm... I'm not super sure I really like this one. 

I really don't like messing with the operation mode on the main unit in the zones, so I don't want to do that in operation_mode.

If we were to go half-way between, where on-off toggles between closed and open / auto (depending on the zone type) would that do what you like?  

I don't want to disable the ability to switch to open mode, when I have it set for outside air (iSave), the device works best if the zones are on open rather than auto, otherwise the vents end up being set on whatever they were set on when it's switched over. This is an error in iSave mode IMHO, but it's something that has to be managed.

**Comment by Swamp-Ig** [comment]
@gcondon1

The head now has an alternative to your PR that keeps the ability to set the zone to open or auto, but also switches on-off if you prefer it.

Non-temp control zones are just on-off.

**Comment by Swamp-Ig** [comment]
More thinking, would it make more sense for this to be a fan mode rather than an operation mode? Then the values of closed/auto/open map fairly neatly to off/auto/high which would be fairly typical fan modes.

**Comment by Swamp-Ig** [comment]
I've pushed out code to do this onto a branch, I don't think ultimately it's how I'm gonna do it though

**Comment by gcondon1** [comment]
This sort of works ok with the HomeKit plug-in, For turning on the aircon and zones, but all zones read as off until turned on through HomeKit

I think its another mapping issues like before for auto/closed vs auto/off

**Comment by Swamp-Ig** [comment]
Doesn't work right with Google home either.

**Comment by Swamp-Ig** [comment]
So I've been having a play around with the google assistant component, I've got it working much better but it will need a patch in HA. I'll submit the PR to homeassistant when I've tested it a bit more.

The assistant component wasn't really handling turn off/turn on for climate controls according to the published google spec. I suspect the homekit one is much the same, will try and have a look at it.

Meanwhile we can probs do some stuff on the branch that does what you've put in so that both assistant and homekit work properly.

**Comment by gcondon1** [comment]
I think functions correctly, as a constant zone stays on regardless of other zones.
If you want it to turn off with the other zones on, then it just becomes a normal zone

**Comment by oompa01** [comment]
Which makes sense as a 'constant' but compared to how the iZone controller
operates it's different.  i.e. even though it's set as a constant zone it
can be turned off assuming one of the others is active.  Would take a bit
of work though in monitoring of other zones

**Comment by Swamp-Ig** [comment]
This is a different issue, I have created a new issue to cover it and copied the comments.

**Comment by Swamp-Ig** [comment]
I've now had the patch to HA accepted so that google home will turn on and off the zone, and the zone will automatically choose auto if it's an auto zone, or open otherwise.
