### ISSUE TITLE
Allow switching constant zones.

### ISSUE THREAD

**Issue by Swamp-Ig** [Swamp-Ig/izone_custom_component#3]
@oompa01

In my setup I have 8 zones one of which is a constant (called downstairs).

On discovery the 7 normal zones are added and work well. For the 8th zone its actually coming up as the main controller (and returns non zone items like mode, fan, etc) but my constant zone isn't appearing. The way we would typically use our system is at night switch on the bedroom zones and turn off downstairs so this doesn't work for us. The constant zone would only kick in if all other zones are off (either manually or auto)

**Comment by Swamp-Ig** [comment]
@gcondon1

I think functions correctly, as a constant zone stays on regardless of other zones.
If you want it to turn off with the other zones on, then it just becomes a normal zone

**Comment by Swamp-Ig** [comment]
@oompa01

Which makes sense as a 'constant' but compared to how the iZone controller
operates it's different.  i.e. even though it's set as a constant zone it
can be turned off assuming one of the others is active.  Would take a bit
of work though in monitoring of other zones

**Comment by Swamp-Ig** [comment]
The 'eighth zone' you're getting is the actual controller itself, it's not that constant zone. 

Does the constant zone need to be turned off and on, monitored, or in any way changed? If so I can get HA to display it, otherwise it's best hidden.

**Comment by oompa01** [comment]
Yeah it's definitely not listing it at all (and agree the eighth I'm seeing is the controller).  Like I said we do often turn on/off the downstairs (constant) zone but the system is smart enough to detect when no zones are on and sets this 'on'.  The iZone controller actually has a special icon next to the zone status when this occurs

**Comment by Swamp-Ig** [comment]
Probably the think to do is to just comment out [this line](https://github.com/Swamp-Ig/izone_custom_component/blob/master/climate/izone.py#L83) and have the constant zone appear.

You can always hide it in HA anyhow if it's not something you need to see in your interface (quite easily with lovelace). 

The other option would be to make constant zones configurable on if they appear or not. That seems kinda like overkill.

**Comment by gcondon1** [comment]
Why not turn the zone in to a normal zone.
Then you can make a switch in home assistant handle some of the use cases. Ie turn off all zones except constant, or turn on all zones except constant.
Or do what I do and create scenes in HomeKit. I have a scene for Living areas and a Scene for Bedrooms

**Comment by Swamp-Ig** [comment]
Yeh that's what happens if you comment out that line. I deliberately filtered out the constant zone in my setup because it just recirculates air back into the input and there's no reason to switch it.

**Comment by Swamp-Ig** [comment]
The constant zone? Yeh that's already implemented, just a matter of removing that line I pointed to. You just get on-off control and nothing else IIRC. The constant zone for my house just recirculates air.

**Comment by oompa01** [comment]
Ok, I'll give it a go.  Your setup sounds interesting though.  So you have an outlet that's near the intake and just recirculated?

**Comment by Swamp-Ig** [comment]
It's just connected straight back into the intake again, there's no vent, literally a loop. The unit can mostly shut down and just take a bit off that loop of air when it's not needed much.

**Comment by Swamp-Ig** [comment]
FYI:am working on this at the moment. Will check in soon

**Comment by Swamp-Ig** [comment]
This should now be fixed. Give it a test.
